### ISSUE TITLE
Build failes wiith failed to load URL / Connection refused 

### ISSUE THREAD

**Issue by carstenheisterkamp** [waliente/phaser-typescript-electron#1]
The final build does not work, that app starts but the html is not loaded.

"build" and "preview" script end with "(node:5402) electron: Failed to load URL: http://localhost:3000/ with error: ERR_CONNECTION_REFUSED" error.

"dev" works as expected.

**Comment by Dan-Mizu** [comment]
you need to set your NODE_ENV environment variable to "production". 

main.js under the electron directory is what checks it when building and uses either localhost or the actual file path of the build.

**Comment by waliente** [comment]
> The final build does not work, that app starts but the html is not loaded.
> 
> "build" and "preview" script end with "(node:5402) electron: Failed to load URL: http://localhost:3000/ with error: ERR_CONNECTION_REFUSED" error.
> 
> "dev" works as expected.


Which node version are yuo using?
